language: node_js

node_js:
- "lts/*"

branches:
  only:
    - master
    - dev

jobs:
  include:
    - stage: deploy
      cache:
          directories:
            - node_modules
      install:
        - npm install -g serverless
        - npm install
      script: 
        - npm run build
        - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - serverless deploy

notifications:
  email:
    on_success: never
    on_failure: always